services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./minio/data:/data
    command: server /data
    restart: unless-stopped

  audio-server:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      - PORT=${PORT:-8080}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT}
      - AWS_S3_USE_SSL=${AWS_S3_USE_SSL}
      - AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
      - AWS_S3_SECRET_KEY=${AWS_S3_SECRET_KEY}
    depends_on:
      - minio
    restart: unless-stopped
