# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy backend to Amazon ECS

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

env:
  AWS_REGION: eu-west-3                                             # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: audio-server-repository                              # set this to your Amazon ECR repository name
  ECS_SERVICE: audio-server-${{ inputs.stage }}-service            # set this to your Amazon ECS service name
  ECS_CLUSTER: audio-server-${{ inputs.stage }}-cluster            # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION_FAMILY: audio-server-${{ inputs.stage }}-td      # set this to the path to your Amazon ECS task definition
  CONTAINER_NAME: audio-server-container                       # set this to the name of the container in the containerDefinitions section of your task definition
  ACCESS_KEY_ID: ${{ (inputs.stage == 'prod') && secrets.AWS_PROD_ACCESS_KEY_ID || secrets.AWS_PREPROD_ACCESS_KEY_ID }}
  ACCESS_KEY_SECRET: ${{ (inputs.stage == 'prod') && secrets.AWS_PROD_ACCESS_KEY_SECRET || secrets.AWS_PREPROD_ACCESS_KEY_SECRET }}

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Setup target dir as cache
#        uses: actions/cache@v4
#        with:
#          path: backend/build/libs/backend.jar
#          key: ${{ inputs.artifact-name }}-${{ github.sha }}
#          enableCrossOsArchive: true
#          fail-on-cache-miss: true

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.ACCESS_KEY_SECRET }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and push it to ECR so that it can be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.stage }}-latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Download task definition
        id: download-task
        run: |
          aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION_FAMILY --query taskDefinition > task-definition.json
          echo "revision=$(cat task-definition.json | jq .revision)" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: De-register previous revision
        run: |
          aws ecs deregister-task-definition \
            --task-definition $ECS_TASK_DEFINITION_FAMILY:${{ steps.download-task.outputs.revision }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          force-new-deployment: true
          wait-for-service-stability: false
